### ISSUE TITLE
TypeError: add_marker() missing 1 required positional argument: 'id'

### ISSUE THREAD

**Issue by ArunLukeDsouza** [UASLab/ImageAnalysis#10]
Thanks a lot for this great project!
I've been trying to create a Mosaic like the one put up on the Readme but I'm facing a frustrating error 

```
Aruns-MacBook-Air:scripts arun$ python3 explorer.py avon-park/images
Notice: cache dir doesn't exist: avon-park/images/ImageAnalysis/cache
Notice: state dir doesn't exist: avon-park/images/ImageAnalysis/state
state: path missing: avon-park/images/ImageAnalysis/state
no histogram templates found...
Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
Loading saved annotations: avon-park/images/ImageAnalysis/annotations.json
Traceback (most recent call last):
  File "explorer.py", line 691, in <module>
    app = MyApp()
  File "explorer.py", line 114, in __init__
    proj, ned_ref, tk_root)
  File "scripts/explore/annotations.py", line 28, in __init__
    self.load()
  File "scripts/explore/annotations.py", line 109, in load
    self.add_marker( ned, "" )
TypeError: add_marker() missing 1 required positional argument: 'id'
``` 

I have used the avon-park dataset and I'm running the code on macOS Big Sur with Python 3.7.0
Please Advise.

**Comment by clolsonus** [comment]
It turns out the avon-park data set had not been updated to match some of the more recent code changes.  I just did that, and changed to the new file link in the README-DataSets file.  Here is the new avon-park data set download.  Hopefully this addresses the issue you are ssing.  As a very short term fix, you could try simply removing the annotations.json file.

http://www.all-aero.com/index.php/component/content/article/126-planes-c/20214-cheranovski-bich-7

I am going to close this issue, but if you continue to have concerns or notice something I missed, please let me know.
